### PR TITLE
Use new serve_static_files

### PR DESCRIPTION
**Pull request by arthurnn**
one rails 4.2+ the option now is called `serve_static_files` , see https://github.com/rails/rails/pull/18100/files , cc @chancancode

r. @schneems @hone

### CODE REVIEW

**Comment by schneems** [comment]
Sorry, i forgot to push, master is now up to date

**Comment by batter** [comment]
@schneems - It'd be nice to get git tags pushed for new releases to GitHub, makes it easier to reference where the release was cut when browsing for code changes.

**Comment by schneems** [comment]
Does rubygems have hooks? I would love to automatically make a git tag when I `gem push`.

**Comment by batter** [comment]
Bundler does actually. You can add a line to a gem's `Rakefile` and it will add a few tasks, one of which is named `release` and will create a tag and then build and push the gem to Rubygems.  I believe you still have to run `git push --tags` to push the tag to GitHub, but it still makes life a lot easier!

[Here's an example of the syntax on a `Rakefile`](https://github.com/airblade/paper_trail/blob/master/Rakefile#L2)

**Pull request merged**
